# Hello Pandas
### Data Science :: Aula 01

* Aqui será documentado meu primeiro contato com a lib **pandas**.

* Os estudos serão orientados de acordo com as [video aulas de **Fabrício Firmino** no youtube](https://www.youtube.com/watch?v=1KYvdVSffU0).

In [1]:
import pandas
#importa a lib pandas

In [2]:
irisDataFrame = pandas.read_csv("iris.csv", header = None)
#cria um data frame com o conteúdo do arquivo iris.csv, e sinaliza que este arquivo não possui header

_**Data Frame** é um tipo de estrutura de dados que a lib nos permite trabalhar._

*Possuem duas dimensões e portanto são especialmente úteis para dados estruturados em **tabelas**.*

*São objetos onde podem ser armazenados diversos outros tipos de dados, como vetores, listas ou outros data frames*

In [3]:
irisDataFrame
#retorna o conteúdo do data frame iris

       0    1    2    3          4
0    5.1  3.5  1.4  0.2     Setosa
1    4.9  3.0  1.4  0.2     Setosa
2    4.7  3.2  1.3  0.2     Setosa
3    4.6  3.1  1.5  0.2     Setosa
4    5.0  3.6  1.4  0.2     Setosa
5    5.4  3.9  1.7  0.4     Setosa
6    4.6  3.4  1.4  0.3     Setosa
7    5.0  3.4  1.5  0.2     Setosa
8    4.4  2.9  1.4  0.2     Setosa
9    4.9  3.1  1.5  0.1     Setosa
10   5.4  3.7  1.5  0.2     Setosa
11   4.8  3.4  1.6  0.2     Setosa
12   4.8  3.0  1.4  0.1     Setosa
13   4.3  3.0  1.1  0.1     Setosa
14   5.8  4.0  1.2  0.2     Setosa
15   5.7  4.4  1.5  0.4     Setosa
16   5.4  3.9  1.3  0.4     Setosa
17   5.1  3.5  1.4  0.3     Setosa
18   5.7  3.8  1.7  0.3     Setosa
19   5.1  3.8  1.5  0.3     Setosa
20   5.4  3.4  1.7  0.2     Setosa
21   5.1  3.7  1.5  0.4     Setosa
22   4.6  3.6  1.0  0.2     Setosa
23   5.1  3.3  1.7  0.5     Setosa
24   4.8  3.4  1.9  0.2     Setosa
25   5.0  3.0  1.6  0.2     Setosa
26   5.0  3.4  1.6  0.4     Setosa
27   5.2  3.5  1.5  0.2     Setosa
28   5.2  3.4  1.4  0.2     Setosa
29   4.7  3.2  1.6  0.2     Setosa
..   ...  ...  ...  ...        ...
120  6.9  3.2  5.7  2.3  Virginica
121  5.6  2.8  4.9  2.0  Virginica
122  7.7  2.8  6.7  2.0  Virginica
123  6.3  2.7  4.9  1.8  Virginica
124  6.7  3.3  5.7  2.1  Virginica
125  7.2  3.2  6.0  1.8  Virginica
126  6.2  2.8  4.8  1.8  Virginica
127  6.1  3.0  4.9  1.8  Virginica
128  6.4  2.8  5.6  2.1  Virginica
129  7.2  3.0  5.8  1.6  Virginica
130  7.4  2.8  6.1  1.9  Virginica
131  7.9  3.8  6.4  2.0  Virginica
132  6.4  2.8  5.6  2.2  Virginica
133  6.3  2.8  5.1  1.5  Virginica
134  6.1  2.6  5.6  1.4  Virginica
135  7.7  3.0  6.1  2.3  Virginica
136  6.3  3.4  5.6  2.4  Virginica
137  6.4  3.1  5.5  1.8  Virginica
138  6.0  3.0  4.8  1.8  Virginica
139  6.9  3.1  5.4  2.1  Virginica
140  6.7  3.1  5.6  2.4  Virginica
141  6.9  3.1  5.1  2.3  Virginica
142  5.8  2.7  5.1  1.9  Virginica
143  6.8  3.2  5.9  2.3  Virginica
144  6.7  3.3  5.7  2.5  Virginica
145  6.7  3.0  5.2  2.3  Virginica
146  6.3  2.5  5.0  1.9  Virginica
147  6.5  3.0  5.2  2.0  Virginica
148  6.2  3.4  5.4  2.3  Virginica
149  5.9  3.0  5.1  1.8  Virginica

[150 rows x 5 columns]

In [4]:
irisDataFrame.columns = ["SepalLength", "SepalWidth", "PetalLength", "PetalWidth", "Name"]
#atribui um header ao data frame caso ele não possua um
#se já possuir um header, ele o altera para este que está sendo passado
#a alteração é feita pela troca da primeira linha do data frame pelo conteúdo passado neste comando

In [5]:
irisDataFrame
#retornando o conteúdo do data frame iris, que agora possui header

     SepalLength  SepalWidth  PetalLength  PetalWidth       Name
0            5.1         3.5          1.4         0.2     Setosa
1            4.9         3.0          1.4         0.2     Setosa
2            4.7         3.2          1.3         0.2     Setosa
3            4.6         3.1          1.5         0.2     Setosa
4            5.0         3.6          1.4         0.2     Setosa
5            5.4         3.9          1.7         0.4     Setosa
6            4.6         3.4          1.4         0.3     Setosa
7            5.0         3.4          1.5         0.2     Setosa
8            4.4         2.9          1.4         0.2     Setosa
9            4.9         3.1          1.5         0.1     Setosa
10           5.4         3.7          1.5         0.2     Setosa
11           4.8         3.4          1.6         0.2     Setosa
12           4.8         3.0          1.4         0.1     Setosa
13           4.3         3.0          1.1         0.1     Setosa
14           5.8         4.0          1.2         0.2     Setosa
15           5.7         4.4          1.5         0.4     Setosa
16           5.4         3.9          1.3         0.4     Setosa
17           5.1         3.5          1.4         0.3     Setosa
18           5.7         3.8          1.7         0.3     Setosa
19           5.1         3.8          1.5         0.3     Setosa
20           5.4         3.4          1.7         0.2     Setosa
21           5.1         3.7          1.5         0.4     Setosa
22           4.6         3.6          1.0         0.2     Setosa
23           5.1         3.3          1.7         0.5     Setosa
24           4.8         3.4          1.9         0.2     Setosa
25           5.0         3.0          1.6         0.2     Setosa
26           5.0         3.4          1.6         0.4     Setosa
27           5.2         3.5          1.5         0.2     Setosa
28           5.2         3.4          1.4         0.2     Setosa
29           4.7         3.2          1.6         0.2     Setosa
..           ...         ...          ...         ...        ...
120          6.9         3.2          5.7         2.3  Virginica
121          5.6         2.8          4.9         2.0  Virginica
122          7.7         2.8          6.7         2.0  Virginica
123          6.3         2.7          4.9         1.8  Virginica
124          6.7         3.3          5.7         2.1  Virginica
125          7.2         3.2          6.0         1.8  Virginica
126          6.2         2.8          4.8         1.8  Virginica
127          6.1         3.0          4.9         1.8  Virginica
128          6.4         2.8          5.6         2.1  Virginica
129          7.2         3.0          5.8         1.6  Virginica
130          7.4         2.8          6.1         1.9  Virginica
131          7.9         3.8          6.4         2.0  Virginica
132          6.4         2.8          5.6         2.2  Virginica
133          6.3         2.8          5.1         1.5  Virginica
134          6.1         2.6          5.6         1.4  Virginica
135          7.7         3.0          6.1         2.3  Virginica
136          6.3         3.4          5.6         2.4  Virginica
137          6.4         3.1          5.5         1.8  Virginica
138          6.0         3.0          4.8         1.8  Virginica
139          6.9         3.1          5.4         2.1  Virginica
140          6.7         3.1          5.6         2.4  Virginica
141          6.9         3.1          5.1         2.3  Virginica
142          5.8         2.7          5.1         1.9  Virginica
143          6.8         3.2          5.9         2.3  Virginica
144          6.7         3.3          5.7         2.5  Virginica
145          6.7         3.0          5.2         2.3  Virginica
146          6.3         2.5          5.0         1.9  Virginica
147          6.5         3.0          5.2         2.0  Virginica
148          6.2         3.4          5.4         2.3  Virginica
149          5.9         3.0          5.1         1.8  Virginica

[150 rows x 5 columns]

In [6]:
irisDataFrame.head(10)
#método para retornar apenas as dez primeiras linhas do data frame

   SepalLength  SepalWidth  PetalLength  PetalWidth    Name
0          5.1         3.5          1.4         0.2  Setosa
1          4.9         3.0          1.4         0.2  Setosa
2          4.7         3.2          1.3         0.2  Setosa
3          4.6         3.1          1.5         0.2  Setosa
4          5.0         3.6          1.4         0.2  Setosa
5          5.4         3.9          1.7         0.4  Setosa
6          4.6         3.4          1.4         0.3  Setosa
7          5.0         3.4          1.5         0.2  Setosa
8          4.4         2.9          1.4         0.2  Setosa
9          4.9         3.1          1.5         0.1  Setosa

In [7]:
irisDataFrame[:10]
#outra maneira de retornar as dez primeiras linhas do data frame

   SepalLength  SepalWidth  PetalLength  PetalWidth    Name
0          5.1         3.5          1.4         0.2  Setosa
1          4.9         3.0          1.4         0.2  Setosa
2          4.7         3.2          1.3         0.2  Setosa
3          4.6         3.1          1.5         0.2  Setosa
4          5.0         3.6          1.4         0.2  Setosa
5          5.4         3.9          1.7         0.4  Setosa
6          4.6         3.4          1.4         0.3  Setosa
7          5.0         3.4          1.5         0.2  Setosa
8          4.4         2.9          1.4         0.2  Setosa
9          4.9         3.1          1.5         0.1  Setosa

In [8]:
irisDataFrame.tail(10)
#retorna as dez ultimas linhas

     SepalLength  SepalWidth  PetalLength  PetalWidth       Name
140          6.7         3.1          5.6         2.4  Virginica
141          6.9         3.1          5.1         2.3  Virginica
142          5.8         2.7          5.1         1.9  Virginica
143          6.8         3.2          5.9         2.3  Virginica
144          6.7         3.3          5.7         2.5  Virginica
145          6.7         3.0          5.2         2.3  Virginica
146          6.3         2.5          5.0         1.9  Virginica
147          6.5         3.0          5.2         2.0  Virginica
148          6.2         3.4          5.4         2.3  Virginica
149          5.9         3.0          5.1         1.8  Virginica

In [9]:
irisDataFrame.shape
#retorna o número de linhas e o número de colunas do data frame

(150, 5)

In [10]:
irisDataFrame[irisDataFrame["Name"] == "Virginica"].shape
#retorna o número de linhas e colunas cujos valores de name são iguais à virginica

(50, 5)

In [11]:
irisDataFrame.count()
#retorna o número de linhas que cada coluna possui
#é especialmente útil para quando o csv está mais bagunçado, como quando possui células vazias por exemplo

SepalLength    150
SepalWidth     150
PetalLength    150
PetalWidth     150
Name           150
dtype: int64

In [12]:
irisDataFrame["Name"].count()
#retorna o número de linhas existentes na coluna "name"

150

In [13]:
irisDataFrame["Name"].value_counts()
#retorna a frequência de cada valor presente na coluna "name"

Setosa        50
Virginica     50
Versicolor    50
Name: Name, dtype: int64

In [14]:
irisDataFrame.dtypes
#retorna os tipos de dados dos valores presentes nas colunas do data frame
#strings são representadas como objetos

SepalLength    float64
SepalWidth     float64
PetalLength    float64
PetalWidth     float64
Name            object
dtype: object

In [15]:
irisDataFrame.describe()
#método que retorna, para cada coluna:
#o número de linhas; a média dos valores; o desvio padrão; o valor mínimo; o valor máximo; e os quartis.

       SepalLength  SepalWidth  PetalLength  PetalWidth
count   150.000000  150.000000   150.000000  150.000000
mean      5.843333    3.057333     3.758000    1.199333
std       0.828066    0.435866     1.765298    0.762238
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.350000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000